source :rubygems

# Project requirements
gem 'rake'
gem 'rack-flash'
gem 'thin' # or mongrel

# Component requirements
gem 'haml'

gem 'rack-perftools_profiler', :require => 'rack/perftools_profiler'

# Test requirements


# Padrino
%w(core gen helpers mailer admin).each do |gem|
  gem 'padrino-' + gem, :path => File.expand_path('../../../../../padrino-' + gem, __FILE__)
end
